version: "3.9"

services:
  controller:
    build: .
    container_name: controller
    ports:
      - "8000:8000"
    environment:
      - CERT_FILE=/app/cert.pem
      - KEY_FILE=/app/key.pem
    volumes:
      - ./controller:/app/controller
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem

  replica1:
    build: .
    container_name: replica1
    ports:
      - "8101:8101"
    environment:
      - MEDIA_ROOT=/app/replica1/media
    command: >
      hypercorn replica1.app:app
      --bind 0.0.0.0:8101
      --certfile=/app/cert.pem
      --keyfile=/app/key.pem
    volumes:
      - ./replica1:/app/replica1
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem

  replica2:
    build: .
    container_name: replica2
    ports:
      - "8102:8102"
    environment:
      - MEDIA_ROOT=/app/replica2/media
    command: >
      hypercorn replica2.app:app
      --bind 0.0.0.0:8102
      --certfile=/app/cert.pem
      --keyfile=/app/key.pem
    volumes:
      - ./replica2:/app/replica2
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem

  replica3:
    build: .
    container_name: replica3
    ports:
      - "8103:8103"
    environment:
      - MEDIA_ROOT=/app/replica3/media
    command: >
      hypercorn replica3.app:app
      --bind 0.0.0.0:8103
      --certfile=/app/cert.pem
      --keyfile=/app/key.pem
    volumes:
      - ./replica3:/app/replica3
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
